// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnimationController from "./animation_controller"
application.register("animation", AnimationController)

import ApplicationController from "./application_controller"
application.register("application", ApplicationController)

import AutoclickController from "./autoclick_controller"
application.register("autoclick", AutoclickController)

import CarmenController from "./carmen_controller"
application.register("carmen", CarmenController)

import ConfirmController from "./confirm_controller"
application.register("confirm", ConfirmController)

import CourseSetup__AidStationCheckboxController from "./course_setup/aid_station_checkbox_controller"
application.register("course-setup--aid-station-checkbox", CourseSetup__AidStationCheckboxController)

import CourseSetup__MainController from "./course_setup/main_controller"
application.register("course-setup--main", CourseSetup__MainController)

import CourseSetup__SplitLocationController from "./course_setup/split_location_controller"
application.register("course-setup--split-location", CourseSetup__SplitLocationController)

import CourseSetup__SplitsTableController from "./course_setup/splits_table_controller"
application.register("course-setup--splits-table", CourseSetup__SplitsTableController)

import DropzoneController from "./dropzone_controller"
application.register("dropzone", DropzoneController)

import EventSetupController from "./event_setup_controller"
application.register("event-setup", EventSetupController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import FormAutoSubmitController from "./form_auto_submit_controller"
application.register("form-auto-submit", FormAutoSubmitController)

import FormDisableSubmitController from "./form_disable_submit_controller"
application.register("form-disable-submit", FormDisableSubmitController)

import FormModalController from "./form_modal_controller"
application.register("form-modal", FormModalController)

import HighlightController from "./highlight_controller"
application.register("highlight", HighlightController)

import InputmaskController from "./inputmask_controller"
application.register("inputmask", InputmaskController)

import LiveEntry__EffortTableController from "./live_entry/effort_table_controller"
application.register("live-entry--effort-table", LiveEntry__EffortTableController)

import LiveEntry__MainController from "./live_entry/main_controller"
application.register("live-entry--main", LiveEntry__MainController)

import LiveEntry__PullTimesController from "./live_entry/pull_times_controller"
application.register("live-entry--pull-times", LiveEntry__PullTimesController)

import LiveEntry__RawTimesPushController from "./live_entry/raw_times_push_controller"
application.register("live-entry--raw-times-push", LiveEntry__RawTimesPushController)

import MapsController from "./maps_controller"
application.register("maps", MapsController)

import MasonryController from "./masonry_controller"
application.register("masonry", MasonryController)

import NavigationController from "./navigation_controller"
application.register("navigation", NavigationController)

import NotificationsController from "./notifications_controller"
application.register("notifications", NotificationsController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)

import RawTimesPushController from "./raw_times_push_controller"
application.register("raw-times-push", RawTimesPushController)

import ResultsTemplateController from "./results_template_controller"
application.register("results-template", ResultsTemplateController)

import SelectGetController from "./select_get_controller"
application.register("select-get", SelectGetController)

import ShiftToggleController from "./shift_toggle_controller"
application.register("shift-toggle", ShiftToggleController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)

import VisibilityController from "./visibility_controller"
application.register("visibility", VisibilityController)
