// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnimationController from "./animation_controller.js"
application.register("animation", AnimationController)

import ApplicationController from "./application_controller.js"
application.register("application", ApplicationController)

import CarmenController from "./carmen_controller.js"
application.register("carmen", CarmenController)

import ConfirmController from "./confirm_controller.js"
application.register("confirm", ConfirmController)

import EventSetupController from "./event_setup_controller.js"
application.register("event-setup", EventSetupController)

import FinishLineController from "./finish_line_controller.js"
application.register("finish-line", FinishLineController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import HighlightController from "./highlight_controller.js"
application.register("highlight", HighlightController)

import InfiniteScrollController from "./infinite_scroll_controller.js"
application.register("infinite-scroll", InfiniteScrollController)

import InputmaskController from "./inputmask_controller.js"
application.register("inputmask", InputmaskController)

import LoginController from "./login_controller.js"
application.register("login", LoginController)

import MapsController from "./maps_controller.js"
application.register("maps", MapsController)

import NavigationController from "./navigation_controller.js"
application.register("navigation", NavigationController)

import NotificationController from "./notification_controller.js"
application.register("notification", NotificationController)

import PopoverController from "./popover_controller.js"
application.register("popover", PopoverController)

import ResultsTemplateController from "./results_template_controller.js"
application.register("results-template", ResultsTemplateController)

import RosterController from "./roster_controller.js"
application.register("roster", RosterController)

import SidebarController from "./sidebar_controller.js"
application.register("sidebar", SidebarController)
