// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AidStationCheckboxController from "./aid_station_checkbox_controller"
application.register("aid-station-checkbox", AidStationCheckboxController)

import AnimationController from "./animation_controller"
application.register("animation", AnimationController)

import AutoclickController from "./autoclick_controller"
application.register("autoclick", AutoclickController)

import AutofocusController from "./autofocus_controller"
application.register("autofocus", AutofocusController)

import CarmenController from "./carmen_controller"
application.register("carmen", CarmenController)

import ConfirmController from "./confirm_controller"
application.register("confirm", ConfirmController)

import CourseSetupController from "./course_setup_controller"
application.register("course-setup", CourseSetupController)

import DropzoneController from "./dropzone_controller"
application.register("dropzone", DropzoneController)

import EventSetupController from "./event_setup_controller"
application.register("event-setup", EventSetupController)

import FinishLineController from "./finish_line_controller"
application.register("finish-line", FinishLineController)

import FormApplyController from "./form_apply_controller"
application.register("form-apply", FormApplyController)

import FormAutoSubmitController from "./form_auto_submit_controller"
application.register("form-auto-submit", FormAutoSubmitController)

import FormModalController from "./form_modal_controller"
application.register("form-modal", FormModalController)

import HighlightController from "./highlight_controller"
application.register("highlight", HighlightController)

import InputmaskController from "./inputmask_controller"
application.register("inputmask", InputmaskController)

import LoginController from "./login_controller"
application.register("login", LoginController)

import MapsController from "./maps_controller"
application.register("maps", MapsController)

import MasonryController from "./masonry_controller"
application.register("masonry", MasonryController)

import NavigationController from "./navigation_controller"
application.register("navigation", NavigationController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)

import ResultsTemplateController from "./results_template_controller"
application.register("results-template", ResultsTemplateController)

import RosterController from "./roster_controller"
application.register("roster", RosterController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import SplitLocationController from "./split_location_controller"
application.register("split-location", SplitLocationController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)

import VisibilityController from "./visibility_controller"
application.register("visibility", VisibilityController)
