desc "Removes users with suspicious names that indicate they were generated by bots"
task :remove_bot_users, [:model] => :environment do
  start_time = Time.current

  suspected_bot_users = User.where("created_at > ?", 2.months.ago)
                            .where("length(first_name) > ? and length(last_name) > ?", 8, 8)
                            .where("initcap(first_name) != first_name and initcap(last_name) != last_name")

  puts "Preparing to remove #{suspected_bot_users.count} users:"
  suspected_bot_users.pluck(:first_name, :last_name).map(&:join).each do |full_name|
    puts full_name
  end
  puts "Proceed? (y/N)"

  answer = STDIN.gets.chomp
  abort "Aborting." unless answer.upcase == "Y"

  suspected_bot_users.each(&:destroy)

  elapsed_time = Time.current - start_time
  puts "\nFinished removing bot users in #{elapsed_time} seconds"
end
