FactoryGirl.define do
  factory :course do
    sequence(:name) { |n| "Course #{n}" }

    factory :course_with_standard_splits do

      transient { splits_count 4 }

      after(:stub) do |course, evaluator|
        course.id = nil
        start_split = build_stubbed(:start_split)
        intermediate_splits = build_stubbed_list(:split, evaluator.splits_count - 2)
        finish_split = build_stubbed(:finish_split)
        splits = [start_split, intermediate_splits, finish_split].flatten

        # Align split_ids with standard split_ids generated by split_time factories
        splits.each_with_index { |split, i| split.id = 101 + i }
        course.splits = splits
      end

      after(:build) do |course, evaluator|
        build(:start_split, course: course)
        build_list(:split, evaluator.splits_count - 2, course: course)
        build(:finish_split, course: course)
      end

      after(:create) do |course, evaluator|
        create(:start_split, course: course)
        create_list(:split, evaluator.splits_count - 2, course: course)
        create(:finish_split, course: course)
      end
    end
  end
end