plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "tmp/**/*"
    - ".git/**/*"
    - "bin/*"
    - "db/**/*"
  TargetRubyVersion: 4.0
  SuggestExtensions: false

Layout/LineLength:
  Exclude:
    - "spec/**/*"

Metrics:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Lint/MissingSuper:
  Enabled: true
  Exclude:
    - "app/presenters/**/*"
    - "lib/etl/transformers/**/*"

Rails/Delegate:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/EnvironmentVariableAccess:
  Enabled: true
  AllowReads: false
  Exclude:
    - "config/initializers/01_ost_config.rb"

Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: true

Rails/RequestReferer:
  Enabled: false

RSpec/BeEq:
  Enabled: false

RSpec/ChangeByZero:
  Enabled: false

RSpec/EmptyLineAfterFinalLet:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/IndexedLet:
  Exclude:
    - "spec/**/*"

RSpec/NoExpectationExample:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - "spec/**/*"

Style/Documentation:
  Enabled: false

Style/OneClassPerFile:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SafeNavigation:
  Enabled: true

Style/HashSyntax:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/OpenStructUse:
  Exclude:
    - "lib/etl/extractors/**/*"
    - "spec/lib/etl/**/*"
