ruby '2.3.3'
source 'https://rubygems.org'
gem 'rails', '~> 4.2.7'
gem 'responders', '~> 2.0'
gem 'bootstrap-sass'
gem 'vuejs-rails'
gem 'sass-rails', '~> 5.0.6'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jquery-fileupload-rails'
gem 'jquery-ui-rails', '~> 5.0'
gem 'switchery-rails'
gem 'jbuilder', '~> 2.0'
gem 'turbolinks'
gem 'high_voltage'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'devise'
gem 'devise-bootstrap-views'
gem 'pundit'
gem 'rails_apps_pages'
gem 'oj'
gem 'alchemist'
gem 'roo'
gem 'roo-xls'
gem 'carmen-rails'
gem 'gmaps4rails'
gem 'better_errors'
gem 'foreman'
gem 'rails_layout'
gem 'will_paginate'
gem 'bootstrap-will_paginate'
gem 'api-pagination'
gem 'twitter-bootstrap-rails'
gem 'bulk_insert'
gem 'descriptive_statistics'
gem 'pg', '~> 0.20.0'
gem 'active_record_union'
gem 'upsert'
gem 'structpluck'
gem 'strip_attributes'
gem 'puma'
gem 'puma_worker_killer'
gem 'sidekiq'
gem 'aws-sdk'
gem 'skylight'
gem 'pusher'
gem 'active_model_serializers'
gem 'friendly_id', '~> 5.1.0'
gem 'jwt'
gem 'momentjs-rails'
gem 'bootstrap3-datetimepicker-rails'
gem 'rest-client'
gem 'sitemap_generator'
gem 'phony_rails'
gem 'font-awesome-rails'
gem 'pg_search'
gem 'smarter_csv'
gem 'american_date'
gem 'paperclip', '~> 5.0.0'

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'bullet'
  gem 'quiet_assets'
  gem 'derailed_benchmarks'
  gem 'rails-erd'
end

group :test do
  gem 'capybara'
  gem 'launchy'
  gem 'guard-rspec'
  gem 'factory_girl_rails', require: false
  gem 'database_cleaner'
end

group :development, :test do
  gem 'pry-rails'
  gem 'pry-rescue'
  gem 'rubocop', '~> 0.36'
  gem 'rspec', '~> 3.4'
  gem 'rspec-rails', '~> 3.0'
  gem 'byebug'
  gem 'spring-commands-rspec'
  gem 'rb-fsevent'
  gem 'pry-byebug'
  gem 'dotenv-rails'
  gem 'active_record_query_trace'
end

group :production do
  gem 'rails_12factor'
end
