ruby "4.0.2"

source "https://rubygems.org"

gem "rails", "~> 8.1.0"

gem "activerecord-import"
gem "active_storage_validations", ">= 0.9.2"
gem "acts_as_list", "~> 0.9"
gem "allowable", "~> 1.1"
gem "american_date"
gem "api-pagination", "~> 7.0"
gem "aws-sdk-rails", "~> 3"
gem "aws-sdk-s3", "~> 1", require: false
gem "aws-sdk-sns", "~> 1", require: false
gem "bootsnap"
gem "capitalize_attributes", ">= 0.2"
gem "carmen"
gem "chartkick"
gem "connection_pool", "~> 2.5"
gem "cssbundling-rails"
gem "csv"
gem "dalli"
gem "data_migrate"
gem "devise"
gem "devise-bootstrap5"
gem "devise-i18n"
gem "faraday"
gem "ffaker"
gem "friendly_id"
gem "fx", ">= 0.6.2"
gem "image_processing"
gem "jsbundling-rails"
gem "jsonapi-serializer"
gem "judoscale-rails"
gem "judoscale-solid_queue"
gem "jwt"
gem "local_time"
gem "madmin", "~> 2.0"
gem "mission_control-jobs"
gem "name_of_person"
gem "normalize_country"
gem "omniauth-facebook", ">= 8.0.0"
gem "omniauth-google-oauth2", ">= 0.8.0"
gem "omniauth-rails_csrf_protection", ">= 1.0.0"
gem "ostruct"
gem "pagy"
gem "paper_trail"
gem "pg"
gem "pg_search"
gem "pretender", "~> 0.3", ">= 0.3.4"
gem "progress_bar"
gem "puma"
gem "pundit"
gem "scenic", ">= 1.5.4"
gem "scout_apm"
gem "scout_apm_logging"
gem "sendgrid-ruby"
gem "shortener"
gem "sitemap_generator"
gem "smarter_csv", require: false
gem "solid_cable"
gem "solid_cache"
gem "solid_cache_dashboard", github: "afomera/solid_cache_dashboard", branch: "main"
gem "solid_queue"
gem "sprockets-rails"
gem "statistics", "~> 1.0"
gem "stimulus-rails"
gem "strip_attributes"
gem "structpluck"
gem "terser"
gem "turbo-rails"

group :development do
  gem "better_errors", ">= 2.3"
  gem "derailed_benchmarks"
  gem "listen"
  gem "rails-erd"
  gem "rails_real_favicon", ">= 0.1.0"
  gem "spring"
  gem "web-console", "~> 3.7", ">= 3.7.0"
end

group :test do
  gem "capybara"
  gem "cuprite"
  gem "factory_bot_rails", require: false
  gem "pry"
  gem "vcr", "~> 6.4"
  gem "webmock", "~> 3.5"
end

group :development, :test do
  gem "brakeman"
  gem "bundler-audit"
  gem "rspec"
  gem "rspec-rails", ">= 4.0.2"
  gem "rubocop"
  gem "rubocop-rails"
  gem "rubocop-rspec"
  gem "spring-commands-rspec"
end
