# frozen_string_literal: true

ruby "3.2.1"

source "https://rubygems.org"

gem "activerecord-import"
gem "active_storage_validations", ">= 0.9.2"
gem "acts_as_list", "~> 0.9"
gem "allowable", "~> 1.1"
gem "american_date"
gem "api-pagination"
gem "aws-sdk-rails", "~> 3"
gem "aws-sdk-s3", "~> 1", require: false
gem "aws-sdk-sns", "~> 1", require: false
gem "bootsnap"
gem "bootstrap", "~> 5.2.3"
gem "bootstrap4-datetime-picker-rails", ">= 0.3.1"
gem "bootstrap-will_paginate"
gem "capitalize_attributes", ">= 0.2"
gem "carmen"
gem "chartkick"
gem "coverband"
gem "dalli"
gem "data_migrate"
gem "devise"
gem "devise-bootstrap-views"
gem "ffaker"
gem "font_awesome5_rails", ">= 1.4.0"
gem "friendly_id"
gem "fx", ">= 0.6.2"
gem "image_processing"
gem "jquery-fileupload-rails", ">= 1.0.0"
gem "jquery-rails", ">= 4.4.0"
gem "jquery-ui-rails", "~> 6.0", ">= 6.0.1"
gem "jsonapi-serializer"
gem "jwt"
gem "local_time"
gem "madmin"
gem "momentjs-rails", ">= 2.20.1"
gem "name_of_person"
gem "normalize_country"
gem "omniauth-facebook", ">= 8.0.0"
gem "omniauth-google-oauth2", ">= 0.8.0"
gem "omniauth-rails_csrf_protection", ">= 1.0.0"
gem "paper_trail"
gem "pg"
gem "pg_search"
gem "pretender", "~> 0.3", ">= 0.3.4"
gem "progress_bar"
gem "puma"
gem "pundit"
gem "rails", "~> 7.0.0"
gem "redis", "~> 4.0"
gem "rest-client"
gem "sassc-rails"
gem "scenic", ">= 1.5.4"
gem "scout_apm"
gem "sentry-rails"
gem "sentry-ruby"
gem "sentry-sidekiq"
gem "shortener"
gem "sidekiq", "< 7.0"
gem "sidekiq-cron"
gem "sitemap_generator"
gem "smarter_csv", require: false
gem "sprockets-rails"
gem "strip_attributes"
gem "structpluck"
gem "terser"
gem "turbo-rails"
gem "vuejs-rails"
gem "webpacker", "< 6.0"
gem "will_paginate", "~> 3.3"

group :development do
  gem "better_errors", ">= 2.3"
  gem "derailed_benchmarks"
  gem "listen"
  gem "rails-erd"
  gem "rails_real_favicon", ">= 0.1.0"
  gem "spring"
  gem "web-console", "~> 3.7", ">= 3.7.0"
end

group :test do
  gem "capybara"
  gem "factory_bot_rails", "~> 5.2", ">= 5.2.0", require: false
  gem "pry"
  gem "vcr", "~> 4.0"
  gem "webdrivers", ">= 4.5.0"
  gem "webmock", "~> 3.5"
end

group :development, :test do
  gem "active_record_query_trace"
  gem "brakeman"
  gem "bundler-audit"
  gem "rspec"
  gem "rspec-rails", ">= 4.0.2"
  gem "rubocop", "~> 0.49"
  gem "spring-commands-rspec"
end
