# Site settings
title: OpenSplitTime Documentation
description: Documentation for OpenSplitTime, the free, open-source ultrarunning event management system
url: "https://splittime.github.io" # Production URL
baseurl: "/OpenSplitTime" # Subpath for GitHub Pages

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
