# Site settings
title: OpenSplitTime Documentation
description: Documentation for OpenSplitTime, the free, open-source ultrarunning event management system
url: "docs.opensplittime.org" # Production URL
baseurl: "" # Subpath not needed; github.io figures it out

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
