# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll", "~> 4.3"

# Jekyll plugins
group :jekyll_plugins do
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
end

# Required for Ruby 3.0+
gem "webrick", "~> 1.8"
